import type { Metadata } from 'next';
import { Geist, Geist_Mono, Nunito } from 'next/font/google';
import { Toaster } from '@/components/ui/sonner';
import ReduxProvider from '@/components/providers/ReduxProvider';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const nunito = Nunito({
  variable: '--font-nunito',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${nunito.variable} antialiased`}
      >
        <ReduxProvider>
          {children}
          <Toaster
            toastOptions={{
              style: {
                background: '#10b981',
                color: '#ffffff',
              },
              className: 'toast-success',
            }}
          />
        </ReduxProvider>
      </body>
    </html>
  );
}
